### ISSUE TITLE
add Time::Moment to Dates section

### ISSUE THREAD

**Issue by karenetheridge** [EnlightenedPerlOrganisation/task-kensho#23]
(I vote yes)

**Comment by haarg** [comment]
+1

**Comment by kentfredric** [comment]
+1.

I'd move to get rid of some of the existing entries as well, or at very least, clarify their reasons for inclusion.

Following discussion on #toolchain, its not clear that any of `Date::Tiny` `DateTime::Tiny` or `Time::Tiny` are actually very useful, given they're all into this "floating timezone" stuff, but profoundly, have "now" methods that assume local timezone ..... 

Its also really not clear how Date::Tiny and DateTime::Tiny differ, if at all.

And DateTime should have some kind of warning label on its usage, because any amount of sophisticated usage is going to want to do date math with it,.... and then roll into the fun problem where DateTime objects are mutable and $date->add( otherdate ) mutates the date in place, so the only responsible use involves lots of $date->clone->add(.... ).

And hence, `DateTime::Moonpig` exists.

And that has its own issues that make it hard to use, like not being amenable to "fuzzy" increments ( ie: can't add 1 month to 2016-01-01 to get 2016-02-01 ), instead, preferring to deal in time units for incrementing..

```
perl -MDateTime::Moonpig -E 'DateTime::Moonpig->new( year => 2016, month => 1, day => 1 )->plus( months => 1 )' 
# Argument "months" isn't numeric in addition
perl -MDateTime::Moonpig -E 'DateTime::Moonpig->new( year => 2016, month => 1, day => 1 )->add( months => 1 )' 
# Do not mutate DateTime objects! (http://rjbs.manxome.org/rubric/entry/1929) at /home/kent/perl5/perlbrew/perls/5.24.0-RC5/lib/site_perl/5.24.0/DateTime/Moonpig.pm line 85.
	DateTime::Moonpig::__ANON__(DateTime::Moonpig=HASH(0x2844e58), DateTime::Duration=HASH(0x21c0800)) called at /home/kent/perl5/perlbrew/perls/5.24.0-RC5/lib/site_perl/5.24.0/x86_64-linux/DateTime.pm line 1688
	DateTime::add(DateTime::Moonpig=HASH(0x2844e58), "months", 1) called at -e line 1
```
